chain_width = 70
edition = "2021"
format_code_in_doc_comments = true
group_imports = "StdExternalCrate"
imports_granularity = "Module"
max_width = 90
merge_derives = false
struct_lit_width = 50
use_field_init_shorthand = true
use_small_heuristics = "Max"
