[package]
name = "typst-library"
version = "0.0.0"
authors = ["The Typst Project Developers"]
edition = "2021"

[lib]
test = false
doctest = false
bench = false

[dependencies]
az = "1"
comemo = "0.2"
csv = "1"
ecow = "0.1"
hayagriva = "0.2"
hypher = "0.1"
kurbo = "0.8"
lipsum = { git = "https://github.com/reknih/lipsum" }
log = "0.4"
once_cell = "1"
roxmltree = "0.14"
rustybuzz = "0.5"
serde_json = "1"
smallvec = "1.10"
syntect = { version = "5", default-features = false, features = [
	"default-syntaxes",
	"regex-fancy",
] }
ttf-parser = "0.18.1"
typed-arena = "2"
typst = { path = ".." }
unicode-bidi = "0.3.5"
unicode-math-class = "0.1"
unicode-script = "0.5"
unicode-segmentation = "1"
xi-unicode = "0.3"
